version: '3.8'

services:
    db:
        image: postgres:16
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        expose:
            - 5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready', '-U', '${POSTGRES_USER}']
            interval: 10s
            timeout: 5s
            retries: 5

    backend:
        build: backend # Dockerfile location
        expose:
            - 8000
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: wget --no-verbose -O /dev/null --tries=1 http://localhost:8000/healthcheck || exit 1
            interval: 10s
            timeout: 5s
            retries: 5

    frontend:
        build: frontend # Dockerfile location
        ports:
            - 8501:8501
        depends_on:
            backend:
                condition: service_healthy

volumes:
    postgres_data:
